"""Generate fresh production secrets and emit a .env.prod template.

USAGE
-----
    python3 scripts/rotate_secrets.py > .env.prod

This is a SCAFFOLDING TOOL. It does NOT mutate any DB or running
process. It writes a fresh, never-before-used set of values to stdout
in dotenv format. The operator then:

    1. Reviews the output (or pipes directly to a chosen file).
    2. Copies the values into the prod secret store (Railway,
       1Password, AWS Secrets Manager, k8s secret, etc.) — NOT into
       a committed file. The .env.prod path above is for staging
       hand-off only.
    3. Applies the new env vars to the prod app process. Restart.

WHAT GETS ROTATED
-----------------
  * JWT_SECRET            — invalidates ALL existing admin / tech /
                            customer sessions at first prod boot
                            after rotation. Users re-login. Safe to
                            rotate at any cadence.
  * PHOTO_URL_SECRET      — invalidates every signed-URL link to a
                            photo / document. Existing pages will
                            re-fetch the parent resource and get a
                            fresh URL automatically. Safe to rotate
                            at any cadence.
  * FIELD_ENCRYPTION_KEY  — *** DESTRUCTIVE *** without a re-encrypt
                            migration. Every encrypted column was
                            sealed with the current key; changing
                            the key without re-encrypting will make
                            every PII field unreadable.
                            For first-prod boot (before any real
                            customer data is written) it's safe to
                            generate fresh here, because the dev DB
                            will be wiped (pre-launch checklist
                            item #4). For mid-prod rotation, see the
                            Phase 2 hardening plan and the
                            re-encryption migration not yet shipped.

OUTPUT FORMAT
-------------
Exactly the same key=value lines used in .env.example, so the
operator can diff to spot accidental drift.
"""
from __future__ import annotations

import secrets
import sys
from datetime import datetime, timezone


def _new_key(nbytes: int = 48) -> str:
    """A URL-safe Base64 string. token_urlsafe(48) yields 64 chars."""
    return secrets.token_urlsafe(nbytes)


def main() -> int:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"# Generated by scripts/rotate_secrets.py at {ts}")
    print("# DO NOT commit this file. Copy values into your prod secret store.")
    print("# Restart the app process after applying. JWT_SECRET rotation invalidates")
    print("# all active sessions; PHOTO_URL_SECRET rotation invalidates signed URLs.")
    print("# FIELD_ENCRYPTION_KEY rotation REQUIRES every encrypted row to be re-sealed")
    print("# (see Phase 2 hardening plan). Only rotate before first real customer data is")
    print("# written, OR after the re-encrypt migration is in place.")
    print()
    print(f"JWT_SECRET={_new_key()}")
    print(f"FIELD_ENCRYPTION_KEY={_new_key()}")
    print(f"PHOTO_URL_SECRET={_new_key(32)}")
    print()
    print("# Operator: set the following manually per environment:")
    print("#   PROD_MODE=true")
    print("#   COOKIE_SECURE=true")
    print("#   DATASTORE_ENCRYPTION_CONFIRMED=yes   # after verifying disk encryption")
    print("#   CORS_ALLOW_ORIGINS=https://app.<prod-domain>,https://portal.<prod-domain>")
    print("#   BOOTSTRAP_ADMIN_USERNAME=<the first super_admin's username>")
    print("#   BOOTSTRAP_ADMIN_PASSWORD=<a strong throwaway; first-login flow forces reset>")
    print("#   BOOTSTRAP_ADMIN_NAME=\"<display name>\"")
    print("#   BOOTSTRAP_ADMIN_EMAIL=<for password-reset flow>")
    print("#   BACKUP_GPG_RECIPIENT=<gpg key id whose PRIVATE half lives OFF-host>")
    return 0


if __name__ == "__main__":
    sys.exit(main())
